* ABSTRACT
Past work in preclinical models of breast cancer and other solid tumors implicated SRC in invasion and metastasis, whereas it functioned as an inhibitor of metastasis in bladder cancer. Here we tested the hypothesis that the role of SRC in metastasis is dependent on molecular subtype membership. Analyses of TCGA and other large public datasets demonstrated that SRC mRNA and protein expression were enriched in tumors assigned to the luminal papillary molecular subtype. Unsupervised hierarchical clustering based on whole transcriptome RNA expression data from a panel of n = 30 human bladder cancer cell lines assigned them to 3 major clusters that corresponded to luminal papillary, genomically unstable, or basal/squamous molecular subtype assignments generated using the Lund or Consensus molecular subtype classifiers, and SRC mRNA expression was also highest in luminal papillary cell lines. Chemical SRC antagonists tended to inhibit migration in luminal papillary cells but increased migration and invasion in basal/squamous lines. Conditional SRC knockdown inhibited migration while upregulating EMT gene expression in luminal papillary RT112 cells, whereas it increased migration while downregulating EMT in genomically unstable UM-UC6 cells. Regardless, these effects did not affect levels or sites of experimental metastasis in vivo. Overall, the results confirm that the effects of SRC inhibition on invasion and migration are heterogeneous and linked to molecular subtype membership. The results have implications for the potential use of SRC pathway inhibitors to block bladder cancer progression in patients.
(234 words)

* INTRODUCTION
The SRC protooncogene was first identified as the causative factor that mediated the transforming effects of an avian leukemia virus. Its human counterpart encodes a 60kD non-receptor tyrosine kinase that has been implicated in cell cycle progression and integrin-mediated adhesion signaling. Early studies in hematopoietic cells and solid tumor cell lines implicated the integrin-dependent effects of SRC in directional motility, invasion, and metastasis. However, studies in preclinical models of bladder cancer concluded that SRC inhibited invasion and metastasis via mechanisms that involved direct phosphorylation of RhoGDI2 and downstream inhibition of caveolin-1 (refs).

Bladder cancers are known to be highly heterogeneous in terms of their invasive and metastatic potentials. Most bladder cancers are superficial low-grade papillary lesions that are prone to recurrence but rarely progress to become life-threatening and metastatic. However, approximately 20-25% of bladder cancers are muscle-invasive at diagnosis, and about half of patients with muscle-invasive bladder cancer (MIBC) ultimately die of metastatic disease. Bladder cancers can also be grouped into basal and luminal molecular subtypes that are similar to those described in breast cancer. Luminal papillary bladder cancers are associated with activating FGFR3 mutations and fusions are associated with better survival outcomes, whereas basal bladder cancers exhibit features of epithelial-to-mesenchymal transition (EMT) and are associated with invasive and metastatic disease at clinical presentation and shorter disease-specific survival. We wondered whether SRC might play different roles in luminal versus basal bladder cancers. We tested this hypothesis using public human bladder cancer bulk RNA expression datasets and a large panel of human bladder cancer cell lines.

* RESULTS [6/9]
** HOLD SUPPLEMENTAL FIGURE 1 [1/2]
*** DONE
CLOSED: [2024-08-09 Fri 14:06]
In one of the cell lines (UM-UC6, GU molecular subtype), saracatinib inhibited transwell migration but bosutinib did not (Supplemental Figure 1). Galunisertib inhibited migration in the UM-UC6 but not the RT112 cells (Supplemental Figure 1).

Inhibition of TGFBR1 is a known off-target effect of saracatinib that is not shared by bosutinib (ref). We therefore compared the effects of galunisertib (a chemical TGFB1 inhibitor), saracatinib, and bosutinib on migration in the UM-UC6 cells.

Exposure of UM-UC6 to the combination of galunisertib plus bosutinib did not inhibit migration significantly more than exposure to galunisertib alone (Supplemental Figure 1).

*** HOLD
Saracatinib and bosutinib but not galunisertib decreased phosphorylation of SRC and its downstream target, FAK, whereas galunisertib but not saracatinib or bosutinib decreased phosphorylation of the TGFBR1 substrate, SMAD2 (Supplemental Figure 1).

** HOLD SUPPLEMENTAL FIGURE 2
Effects of conditional SRC knockdown. The effects of saracatinib on SMAD phosphorylation raised concerns about relying on it to identify the direct mechanistic consequences of SRC inhibition. We therefore stably transduced the RT112 and UM-UC6 cells with a lentiviral construct encoding a doxycycline-inducible shRNA construct targeting SRC (or a non-targeting control virus) to test the effects of conditional knockdown on whole transcriptome RNA expression, migration, and metastasis. Preliminary experiments confirmed that doxycycline exposure led to time-dependent suppression of SRC expression in both cell lines (Supplemental Figure 2).

** DONE SUPPLEMENTAL FIGURE 3
CLOSED: [2024-08-12 Mon 11:15]
Doxycycline also caused some growth inhibition in the UM-UC6 cells but had no effect on RT112 (Supplemental Figure 3).
*** NOTE
Debatable. Depends on how wishfully you look at these plots. It certainly doesn't look like RT112 has a sensitivity that is specific to the 004 though. It's not super clear cut though.
** DONE FIGURE 5 [2/2]
CLOSED: [2024-08-12 Mon 16:44]
*** KILL
CLOSED: [2024-08-12 Mon 16:09]
Whole transcriptome RNA expression profiling and GSEA revealed that SRC knockdown increased EMT pathway gene expression in RT112 but decreased expression in UM-UC6, contrary to expectations (Figure 5).

**** NOTE
Unclear how to show this without it looking a little ridiculously cherry-picky. The EMT HM signature that goes down significantly in UC6 does not change significantly in RT112. Also, the signature that change significantly in RT112 do not change significantly in UC6.

One way of going about doing this MIGHT be to do a GSVA and then show score changes in all signatures (significant or not). Will have to see.

After swishing this one about I'm going to say that this is a challenging hypothesis to support.

What about proliferation?

** TODO FIGURE 6 [1/5]
*** HOLD
To examine the effects of SRC inhibition in vivo, we pretreated the RT112 and UM-UC6 cells with doxycycline before inoculating them into the tail veins of immunodeficient NSG mice housed with or without doxycycline in their drinking water. RT112 produced metastases in the lungs, liver, and spine, resulting in failure to void and hind leg paralysis, whereas UM-UC6 caused lymph node and lung metastases (Figure 6).
*** HOLD
and it did not affect the sites of metastasis in either model (Figure 6).
*** HOLD
Immunohistochemical staining and quantitative PCR confirmed sustained SRC knockdown in the metastases (Figure 6).
*** HOLD
Consistent with the in vitro findings, SRC knockdown caused decreased proliferation in the UM-UC6 metastases but had no effect on proliferation in RT112, and knockdown had no measurable effect on proliferation in either model (Figure 6).
* DISCUSSION
* TASKS [1/4]
** TODO Saracatinib, Bosutinib, Galunisertib WB
- UC6, RT112
- SRC, FAK, pSRC, pFAK, SMAD2, pSMAD2
- Timepoint?
- 1uM
** TODO UC6, RT112 SRC iKD doxycycline timecourse (RNA, protein)
** TODO Methods
** DONE Captions
CLOSED: [2024-08-13 Tue 16:52]
