* RESULTS [6/9]
** HOLD SUPPLEMENTAL FIGURE 1 [1/2]
*** DONE
CLOSED: [2024-08-09 Fri 14:06]
In one of the cell lines (UM-UC6, GU molecular subtype), saracatinib inhibited transwell migration but bosutinib did not (Supplemental Figure 1). Galunisertib inhibited migration in the UM-UC6 but not the RT112 cells (Supplemental Figure 1).

Inhibition of TGFBR1 is a known off-target effect of saracatinib that is not shared by bosutinib (ref). We therefore compared the effects of galunisertib (a chemical TGFB1 inhibitor), saracatinib, and bosutinib on migration in the UM-UC6 cells.

Exposure of UM-UC6 to the combination of galunisertib plus bosutinib did not inhibit migration significantly more than exposure to galunisertib alone (Supplemental Figure 1).

*** HOLD
Saracatinib and bosutinib but not galunisertib decreased phosphorylation of SRC and its downstream target, FAK, whereas galunisertib but not saracatinib or bosutinib decreased phosphorylation of the TGFBR1 substrate, SMAD2 (Supplemental Figure 1).

** HOLD SUPPLEMENTAL FIGURE 2
Effects of conditional SRC knockdown. The effects of saracatinib on SMAD phosphorylation raised concerns about relying on it to identify the direct mechanistic consequences of SRC inhibition. We therefore stably transduced the RT112 and UM-UC6 cells with a lentiviral construct encoding a doxycycline-inducible shRNA construct targeting SRC (or a non-targeting control virus) to test the effects of conditional knockdown on whole transcriptome RNA expression, migration, and metastasis. Preliminary experiments confirmed that doxycycline exposure led to time-dependent suppression of SRC expression in both cell lines (Supplemental Figure 2).

** DONE SUPPLEMENTAL FIGURE 3
CLOSED: [2024-08-12 Mon 11:15]
Doxycycline also caused some growth inhibition in the UM-UC6 cells but had no effect on RT112 (Supplemental Figure 3).
*** NOTE
Debatable. Depends on how wishfully you look at these plots. It certainly doesn't look like RT112 has a sensitivity that is specific to the 004 though. It's not super clear cut though.
** DONE FIGURE 5 [2/2]
CLOSED: [2024-08-12 Mon 16:44]
*** KILL
CLOSED: [2024-08-12 Mon 16:09]
Whole transcriptome RNA expression profiling and GSEA revealed that SRC knockdown increased EMT pathway gene expression in RT112 but decreased expression in UM-UC6, contrary to expectations (Figure 5).

**** NOTE
Unclear how to show this without it looking a little ridiculously cherry-picky. The EMT HM signature that goes down significantly in UC6 does not change significantly in RT112. Also, the signature that change significantly in RT112 do not change significantly in UC6.

One way of going about doing this MIGHT be to do a GSVA and then show score changes in all signatures (significant or not). Will have to see.

After swishing this one about I'm going to say that this is a challenging hypothesis to support.

What about proliferation?

** TODO FIGURE 6 [1/5]
*** HOLD
To examine the effects of SRC inhibition in vivo, we pretreated the RT112 and UM-UC6 cells with doxycycline before inoculating them into the tail veins of immunodeficient NSG mice housed with or without doxycycline in their drinking water. RT112 produced metastases in the lungs, liver, and spine, resulting in failure to void and hind leg paralysis, whereas UM-UC6 caused lymph node and lung metastases (Figure 6).
*** HOLD
and it did not affect the sites of metastasis in either model (Figure 6).
*** HOLD
Immunohistochemical staining and quantitative PCR confirmed sustained SRC knockdown in the metastases (Figure 6).
*** HOLD
Consistent with the in vitro findings, SRC knockdown caused decreased proliferation in the UM-UC6 metastases but had no effect on proliferation in RT112, and knockdown had no measurable effect on proliferation in either model (Figure 6).
* TASKS [1/4]
** TODO Saracatinib, Bosutinib, Galunisertib WB
- UC6, RT112
- SRC, FAK, pSRC, pFAK, SMAD2, pSMAD2
- Timepoint?
- 1uM
** TODO UC6, RT112 SRC iKD doxycycline timecourse (RNA, protein)
** TODO Methods
** DONE Captions
CLOSED: [2024-08-13 Tue 16:52]
